runtime: python37
default_expiration: '2s'

handlers:
- url: /
  static_files: serverless-qtree-1/index.html
  upload: serverless-qtree-1/index.html
  expiration: '2s'

- url: /
  static_dir: serverless-qtree-1
  expiration: '2s'
